name: PetsPlus
main: tech.mistermel.petsplus.PetsPlus
author: MisterMel
version: 1.2.0
description: Interactive pets for your players
api-version: 1.13
commands:
  pets:
    description: The main command for PetsPlus.
    aliases: [petsplus]